### ISSUE TITLE
If seeking over the loop point, track doesn't loop

### ISSUE THREAD

**Issue by jpcima** [Wohlstand/BW_Midi_Sequencer#4] opened 2019-12-04 15:58 UTC
It can be tried with a track off the FF7 MIDI set.
eg: `ff7-2-14` moderately short and has a loop point a bit advanced in the file

Here is the player which has just enabled the tag-based loops.
https://github.com/jpcima/midiplay/tree/bw-sequencer

It's how to reproducible it:
- press "`" key once (or whichever key is above TAB)
  such that repeat mode is REPEAT and not MULTI
- press shift+right some times to seek towards end
- player loops it back to 00:00

another note, it's that seeking seemed to get slower and slower with the more loops it does

**Comment by Wohlstand** [comment] 2019-12-04 16:20
Yeah, an old issue, I want to fix it, but I was lazy...

**Comment by Wohlstand** [comment] 2019-12-04 16:28
The reason is that while scanning I don't handling loop points to avoid a possibile infinite loop, however, this is possible to fix this case...

**Comment by jpcima** [comment] 2019-12-04 16:32
What about resetting the loop state, and replaying loop events from the start as they arrive?
Is this not the same case as normal seeking?

**Comment by Wohlstand** [comment] 2019-12-04 16:37
Loop seeking is doing by an absolute position snapshot that is taking from a backup and continuing

**Comment by Wohlstand** [comment] 2019-12-04 16:53
The problem is that snapshot is appearing in only a first passing of loop start while playing. It should be captured on a load time.

**Comment by Wohlstand** [comment] 2021-10-26 01:17
Fixed by 4014128c93176f0cd1b4f6185297b9eec1160b8d

**Closed as completed by Wohlstand** 2021-10-26 01:17 UTC
Labels: bug
